# Generated by Django 6.0.2 on 2026-02-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='revenue',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
