# Generated by Django 6.0.2 on 2026-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_url',
            field=models.CharField(default='https://api.openai.com/v1', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='model',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
    ]
